using MVCLearning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLearning.Controllers
{
    public class EmployeeController : Controller
    {
        public ActionResult EmployeeList()
        {
            var list = new Employees().CreateEmployees();
            return View(list);
        }

        public ActionResult Create_UsingAutoGeneratedForm()
        {
            var employee = new Employee { AddDate = DateTime.Now };
            return View(employee);
        }
    }
}