//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLearning.SampleWCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleWCFServiceReference.ISampleWCFService")]
    public interface ISampleWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWCFService/SampleMethod", ReplyAction="http://tempuri.org/ISampleWCFService/SampleMethodResponse")]
        string SampleMethod(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWCFService/SampleMethod", ReplyAction="http://tempuri.org/ISampleWCFService/SampleMethodResponse")]
        System.Threading.Tasks.Task<string> SampleMethodAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWCFService/ServiceAsyncMethod", ReplyAction="http://tempuri.org/ISampleWCFService/ServiceAsyncMethodResponse")]
        string ServiceAsyncMethod(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWCFService/ServiceAsyncMethod", ReplyAction="http://tempuri.org/ISampleWCFService/ServiceAsyncMethodResponse")]
        System.Threading.Tasks.Task<string> ServiceAsyncMethodAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleWCFServiceChannel : MVCLearning.SampleWCFServiceReference.ISampleWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWCFServiceClient : System.ServiceModel.ClientBase<MVCLearning.SampleWCFServiceReference.ISampleWCFService>, MVCLearning.SampleWCFServiceReference.ISampleWCFService {
        
        public SampleWCFServiceClient() {
        }
        
        public SampleWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SampleMethod(string msg) {
            return base.Channel.SampleMethod(msg);
        }
        
        public System.Threading.Tasks.Task<string> SampleMethodAsync(string msg) {
            return base.Channel.SampleMethodAsync(msg);
        }
        
        public string ServiceAsyncMethod(string msg) {
            return base.Channel.ServiceAsyncMethod(msg);
        }
        
        public System.Threading.Tasks.Task<string> ServiceAsyncMethodAsync(string msg) {
            return base.Channel.ServiceAsyncMethodAsync(msg);
        }
    }
}
